export const autocompleteData = [
    "Apple",
    "Amazon",
    "Artificial Intelligence",
    "Automation",
    "Big Data",
    "Blockchain",
    "Business Analytics",
    "Cloud Computing",
    "Cybersecurity",
    "Data Science",
    "Digital Marketing",
    "E-commerce",
    "Elon Musk",
    "Facebook",
    "Google",
    "Healthcare",
    "Internet of Things",
    "JavaScript",
    "Machine Learning",
    "Microsoft",
    "Mobile Apps",
    "Netflix",
    "New York Times",
    "Online Courses",
    "Python",
    "Quantum Computing",
    "Remote Work",
    "Robotics",
    "Social Media",
    "SpaceX",
    "Startups",
    "Stock Market",
    "Technology Trends",
    "Tesla",
    "Twitter",
    "Virtual Reality",
    "Web Development",
    "YouTube",
    "Augmented Reality",
    "Biotechnology",
    "Clean Energy",
    "Cryptocurrency",
    "Digital Transformation",
    "Electric Vehicles",
    "Fintech",
    "Freelancing",
    "Gig Economy",
    "Green Technology",
    "Home Automation",
    "Internet Security",
    "Investment Strategies",
    "Mobile Payment",
    "Open Source Software",
    "Personal Finance",
    "Podcasting",
    "Renewable Energy",
    "SEO Optimization",
    "Smart Cities",
    "Software Development",
    "Streaming Services",
    "Telemedicine",
    "Virtual Meetings",
    "Wearable Technology",
    "Work-Life Balance",
    "3D Printing",
    "5G Technology",
    "Agritech",
    "Blockchain Technology",
    "Coding Bootcamps",
    "Cyber Attacks",
    "Data Privacy",
    "DevOps",
    "E-learning",
    "Fitness Trackers",
    "Green Energy",
    "Influencer Marketing",
    "Insurtech",
    "IT Infrastructure",
    "Legal Tech",
    "Logistics Technology",
    "Medtech",
    "Nanotechnology",
    "Online Banking",
    "Remote Education",
    "Smart Home Devices",
    "Space Exploration",
    "Sustainable Living",
    "Tech News",
    "Tech Startups",
    "Travel Tech",
    "Urban Mobility",
    "Video Conferencing",
    "Voice Assistants",
    "Wearables",
    "Work from Home",
    "AI Ethics",
    "Autonomous Vehicles",
    "Climate Tech",
    "Digital Nomad",
    "Edtech",
    "Healthtech"
  ];
  